version: '3.8'

services:
  security-audit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["--cve", "--quick"]
    # volumes:
    #   - /var/log:/var/log:ro
    restart: "no"
